version: '3.8'

services:
    gateway:
        image: nginx:latest
        ports:
            - '80:80'
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - auth-service
            - user-service
            - ws-service

    auth-service:
        build: ./auth-service
        environment:
            PORT: 3001
            DB_CONN_STRING: 'oracle_db_url'
        ports:
            - '3001:3001'

    user-service:
        build: ./user-service
        environment:
            PORT: 3002
            AUTH_SERVICE_URL: 'http://auth-service:3001'
        ports:
            - '3002:3002'

    ws-service:
        build: ./ws-service
        environment:
            PORT: 3003
            AUTH_SERVICE_URL: 'http://auth-service:3001'
        ports:
            - '3003:3003'
