version: '3.8'

services:
    express-app:
        # Вказуємо Docker збирати образ з поточного каталогу
        build:
            # Контекстом збірки залишається корінь проєкту (крапка)
            # Саме звідси Docker копіюватиме src/, package.json тощо.
            context: .

            # Шлях до Dockerfile відносно вказаного контексту
            dockerfile: Dockerfile

        # Назва контейнера в системі
        container_name: my-express-server

        # Мапимо порти (порт на комп'ютері:порт всередині контейнера)
        ports:
            - '3000:3000'

        # Підключаємо ваш локальний файл .env (Docker сам прокине змінні в Node.js)
        env_file:
            - .env

        # Створюємо місток для логів (папка на комп'ютері : папка в контейнері).
        # Тепер логи не зникнуть при перезапуску, а з'являться у вашій локальній папці ./logs
        volumes:
            - ./logs:/app/logs

        # Автоматично вмикає вбудовану утиліту tini (розв'язує проблему зі складними npm скриптами)
        init: true

        # Правило перезапуску додатка у разі неочікуваного падіння коду
        restart: always

#
# docker compose up --build -d        --> Збирає образ (враховуючи всі зміни коду), підхоплює .env, створює папку logs та запускає сервер у фоновому режимі (-d)
# docker compose logs -f express-app  --> Показує живий вивід (консоль) вашого Express додатка прямо у терміналі.
# docker compose down                 --> Зупиняє та повністю прибирає контейнер, але ваші збережені файли логів та код залишаються недоторканими
