-- Файл: auth_service_schema.sql

-- Порада: Якщо потрібен NUMBER замість RAW(16):
-- Замініть id RAW(16) DEFAULT SYS_GUID() -> id NUMBER GENERATED BY DEFAULT AS IDENTITY
-- Замініть відповідні зовнішні ключі (user_id, role_id тощо) на NUMBER


-- Основна таблиця ідентифікації
CREATE TABLE USERS (
    id RAW(16) DEFAULT SYS_GUID(),
    username VARCHAR2(50) NOT NULL,
    email VARCHAR2(255),
    password_hash VARCHAR2(255) NOT NULL,
    max_sessions NUMBER(3) DEFAULT 1, -- 0/NULL = безліміт
    is_active NUMBER(1) DEFAULT 1,
    is_verified NUMBER(1) DEFAULT 0,
    failed_attempts NUMBER(1) DEFAULT 0,
    lock_until TIMESTAMP,
    description VARCHAR2(500),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by RAW(16),
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_by RAW(16),
    deleted_at TIMESTAMP, -- NULL = активний, NOT NULL = видалений
    deleted_by RAW(16),
    -- Constraints
    CONSTRAINT PK_USERS PRIMARY KEY (id),
    CONSTRAINT UK_USERS_USERNAME UNIQUE (username),
    CONSTRAINT CK_USERS_ACTIVE CHECK (is_active IN (0, 1)),
    CONSTRAINT CK_USERS_VERIFIED CHECK (is_verified IN (0, 1))
);

-- Індекси
CREATE INDEX IDX_USERS_LOGIN_ACT ON USERS(username, deleted_at);

-- Коментарі
COMMENT ON TABLE USERS IS 'Облікові записи для аутентифікації користувачів';
COMMENT ON COLUMN USERS.id IS 'Первинний ключ (UUID або NUMBER)';
COMMENT ON COLUMN USERS.username IS 'Унікальне ім’я користувача (логін)';
COMMENT ON COLUMN USERS.email IS 'Електронна пошта для сповіщень та скидання пароля';
COMMENT ON COLUMN USERS.password_hash IS 'Хешований пароль (BCrypt/Argon2)';
COMMENT ON COLUMN USERS.max_sessions IS 'Максимальна кількість одночасних сесій (0 - безліміт)';
COMMENT ON COLUMN USERS.is_active IS 'Флаг активності: 1 - ок, 0 - заблоковано адміном';
COMMENT ON COLUMN USERS.is_verified IS 'Чи підтверджено Email (1 - так, 0 - ні)';
COMMENT ON COLUMN USERS.failed_attempts IS 'Кількість невдалих спроб входу поспіль';
COMMENT ON COLUMN USERS.lock_until IS 'Час, до якого аккаунт заморожено через невдалі спроби входу';
COMMENT ON COLUMN USERS.description IS 'Додаткові технічні примітки про користувача';
COMMENT ON COLUMN USERS.created_at IS 'Системна дата створення запису';
COMMENT ON COLUMN USERS.created_by IS 'ID ініціатора створення (адмін або система)';
COMMENT ON COLUMN USERS.updated_at IS 'Системна дата останньої модифікації';
COMMENT ON COLUMN USERS.updated_by IS 'ID того, хто останній редагував профіль';
COMMENT ON COLUMN USERS.deleted_at IS 'Мітка "м’якого видалення" (Soft Delete)';
COMMENT ON COLUMN USERS.deleted_by IS 'ID того, хто виконав видалення користувача';

-- Тригери
CREATE OR REPLACE TRIGGER TRG_USERS_UPD
BEFORE UPDATE ON USERS FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;

    -- Якщо проставлено дату видалення, анулюємо сесії
    IF :OLD.deleted_at IS NULL AND :NEW.deleted_at IS NOT NULL THEN
        UPDATE USER_SESSIONS SET is_revoked = 1 WHERE user_id = :OLD.id;
    END IF;
END;



-- Ролі (RBAC)
CREATE TABLE ROLES (
    id RAW(16) DEFAULT SYS_GUID(),
    role_name VARCHAR2(50) NOT NULL,
    description VARCHAR2(500),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP,
    deleted_by RAW(16),
    -- Constraints
    CONSTRAINT PK_ROLES PRIMARY KEY (id),
    CONSTRAINT UK_ROLES_NAME UNIQUE (role_name)
);

--
COMMENT ON TABLE ROLES IS 'Довідник системних ролей (RBAC)';
COMMENT ON COLUMN ROLES.id IS 'Первинний ключ ролі';
COMMENT ON COLUMN ROLES.role_name IS 'Унікальний код ролі (напр. ROLE_ADMIN)';
COMMENT ON COLUMN ROLES.description IS 'Опис прав, які надає ця роль';
COMMENT ON COLUMN ROLES.created_at IS 'Дата створення ролі';
COMMENT ON COLUMN ROLES.updated_at IS 'Дата останньої зміни назви чи опису';
COMMENT ON COLUMN ROLES.deleted_at IS 'Мітка видалення ролі';
COMMENT ON COLUMN ROLES.deleted_by IS 'Хто видалив роль з системи';


-- Зв'язок Користувач-Роль
CREATE TABLE USER_ROLES (
    user_id RAW(16) NOT NULL,
    role_id RAW(16) NOT NULL,
    assigned_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    assigned_by RAW(16),
    -- Constraints
    CONSTRAINT PK_USER_ROLES PRIMARY KEY (user_id, role_id),
    CONSTRAINT FK_UR_USER FOREIGN KEY (user_id) REFERENCES USERS (id) ON DELETE CASCADE,
    CONSTRAINT FK_UR_ROLE FOREIGN KEY (role_id) REFERENCES ROLES (id) ON DELETE CASCADE
);

--
CREATE INDEX IDX_UR_USER ON USER_ROLES(user_id);

--
COMMENT ON TABLE USER_ROLES IS 'Таблиця зв’язку Many-to-Many між користувачами та ролями';
COMMENT ON COLUMN USER_ROLES.user_id IS 'Посилання на користувача';
COMMENT ON COLUMN USER_ROLES.role_id IS 'Посилання на роль';
COMMENT ON COLUMN USER_ROLES.assigned_at IS 'Коли роль була призначена';
COMMENT ON COLUMN USER_ROLES.assigned_by IS 'Хто призначив роль даному користувачу';



-- Керування сесіями та Refresh токенами
CREATE TABLE USER_SESSIONS (
    id RAW(16) DEFAULT SYS_GUID(),
    user_id RAW(16) NOT NULL,
    refresh_token_hash VARCHAR2(512) NOT NULL,
    device_fingerprint VARCHAR2(255),
    device_info VARCHAR2(255),
    ip_address VARCHAR2(45),
    is_revoked NUMBER(1) DEFAULT 0,
    last_activity TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    -- Constraints
    CONSTRAINT PK_USER_SESSIONS PRIMARY KEY (id),
    CONSTRAINT FK_SESS_USER FOREIGN KEY (user_id) REFERENCES USERS (id) ON DELETE CASCADE,
    CONSTRAINT CK_SESS_REVOKED CHECK (is_revoked IN (0, 1))
);

--
CREATE INDEX IDX_SESS_USER_ACTIVE ON USER_SESSIONS(user_id, expires_at, is_revoked);
-- Пришвидшує пошук сесій для видалення (expired або revoked)
CREATE INDEX IDX_SESS_CLEANUP ON USER_SESSIONS(expires_at, is_revoked);

--
COMMENT ON TABLE USER_SESSIONS IS 'Активні Refresh-сесії та дані пристроїв користувача';
COMMENT ON COLUMN USER_SESSIONS.id IS 'ID сесії (JTI у контексті JWT)';
COMMENT ON COLUMN USER_SESSIONS.user_id IS 'Власник сесії';
COMMENT ON COLUMN USER_SESSIONS.refresh_token_hash IS 'Хешований Refresh-токен для безпечної перевірки';
COMMENT ON COLUMN USER_SESSIONS.device_fingerprint IS 'Цифровий відбиток браузера/пристрою';
COMMENT ON COLUMN USER_SESSIONS.device_info IS 'Текстова інформація про пристрій (User-Agent)';
COMMENT ON COLUMN USER_SESSIONS.ip_address IS 'IP-адреса, з якої було здійснено вхід';
COMMENT ON COLUMN USER_SESSIONS.is_revoked IS 'Чи була сесія примусово завершена (Logout/Admin)';
COMMENT ON COLUMN USER_SESSIONS.last_activity IS 'Дата останнього звернення з цим токеном';
COMMENT ON COLUMN USER_SESSIONS.expires_at IS 'Дата закінчення терміну дії сесії';
COMMENT ON COLUMN USER_SESSIONS.created_at IS 'Час створення сесії (Login)';

-- --
-- CREATE OR REPLACE PROCEDURE PRC_CLEANUP_EXPIRED_SESSIONS AS
-- BEGIN
--     -- Видаляємо прострочені або анульовані сесії
--     DELETE FROM USER_SESSIONS
--     WHERE expires_at < CURRENT_TIMESTAMP
--        OR is_revoked = 1;

--     COMMIT;
-- EXCEPTION
--     WHEN OTHERS THEN
--         ROLLBACK;
--         -- Тут можна додати запис у лог помилок, якщо він у вас є
--         RAISE;
-- END;

-- BEGIN
--     DBMS_SCHEDULER.CREATE_JOB (
--         job_name        => 'JOB_CLEANUP_SESSIONS',
--         job_type        => 'STORED_PROCEDURE',
--         job_action      => 'PRC_CLEANUP_EXPIRED_SESSIONS',
--         start_date      => SYSTIMESTAMP,
--         repeat_interval => 'FREQ=HOURLY; INTERVAL=1', -- Кожну годину
--         enabled         => TRUE,
--         comments        => 'Автоматичне видалення старих та анульованих сесій користувачів'
--     );
-- END;
