-- =============================================================================
-- AUTH SERVICE SCHEMA (EXTENDED RBAC + AUDIT)
-- =============================================================================
-- ПРИМІТКА: Для переходу на NUMBER змініть "RAW(16) DEFAULT SYS_GUID()"
-- на "NUMBER GENERATED BY DEFAULT AS IDENTITY"
-- =============================================================================

-- 1. ТАБЛИЦЯ ПРАВ (Атомарні дозволи)
CREATE TABLE PERMISSIONS (
    id          RAW(16) DEFAULT SYS_GUID(),
    perm_code   VARCHAR2(100) NOT NULL, -- Напр: 'USER_DELETE', 'REPORT_VIEW'
    description VARCHAR2(500),
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_PERMISSIONS PRIMARY KEY (id),
    CONSTRAINT UK_PERM_CODE UNIQUE (perm_code)
);

COMMENT ON TABLE PERMISSIONS IS 'Довідник атомарних системних дозволів';
COMMENT ON COLUMN PERMISSIONS.id IS 'Первинний ключ права';
COMMENT ON COLUMN PERMISSIONS.perm_code IS 'Унікальний рядковий код права для перевірки в коді';
COMMENT ON COLUMN PERMISSIONS.description IS 'Опис того, що дозволяє дане право';
COMMENT ON COLUMN PERMISSIONS.created_at IS 'Дата створення запису';


-- 2. ТАБЛИЦЯ РОЛЕЙ
CREATE TABLE ROLES (
    id          RAW(16) DEFAULT SYS_GUID(),
    role_name   VARCHAR2(50) NOT NULL,
    description VARCHAR2(500),
    is_system   NUMBER(1) DEFAULT 0, -- Системні ролі не можна видаляти
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_ROLES PRIMARY KEY (id),
    CONSTRAINT UK_ROLES_NAME UNIQUE (role_name)
);

COMMENT ON TABLE ROLES IS 'Групи прав (ролі)';
COMMENT ON COLUMN ROLES.role_name IS 'Назва ролі (напр. ADMIN, MANAGER)';
COMMENT ON COLUMN ROLES.is_system IS 'Прапор системної ролі: 1 - так, 0 - ні';


-- 3. ЗВ'ЯЗОК РОЛЬ-ПРАВО (Матриця доступу)
CREATE TABLE ROLE_PERMISSIONS (
    role_id RAW(16) NOT NULL,
    perm_id RAW(16) NOT NULL,
    CONSTRAINT PK_ROLE_PERMISSIONS PRIMARY KEY (role_id, perm_id),
    CONSTRAINT FK_RP_ROLE FOREIGN KEY (role_id) REFERENCES ROLES (id) ON DELETE CASCADE,
    CONSTRAINT FK_RP_PERM FOREIGN KEY (perm_id) REFERENCES PERMISSIONS (id) ON DELETE CASCADE
);

COMMENT ON TABLE ROLE_PERMISSIONS IS 'Прив’язка прав до конкретних ролей';
COMMENT ON COLUMN ROLE_PERMISSIONS.role_id IS 'ID ролі';
COMMENT ON COLUMN ROLE_PERMISSIONS.perm_id IS 'ID права';


-- 4. ТАБЛИЦЯ КОРИСТУВАЧІВ (з полями безпеки)
CREATE TABLE USERS (
    id               RAW(16) DEFAULT SYS_GUID(),
    username         VARCHAR2(50) NOT NULL,
    email            VARCHAR2(255) NOT NULL,
    password_hash    VARCHAR2(255) NOT NULL,
    mfa_secret       VARCHAR2(100), -- Для Google Authenticator
    failed_attempts  NUMBER(2) DEFAULT 0,
    lock_until       TIMESTAMP,
    is_active        NUMBER(1) DEFAULT 1,
    created_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_at       TIMESTAMP,
    CONSTRAINT PK_USERS PRIMARY KEY (id),
    CONSTRAINT UK_USERS_USERNAME UNIQUE (username),
    CONSTRAINT UK_USERS_EMAIL UNIQUE (email)
);

COMMENT ON TABLE USERS IS 'Користувачі системи';
COMMENT ON COLUMN USERS.mfa_secret IS 'Секретний ключ для двофакторної аутентифікації';
COMMENT ON COLUMN USERS.failed_attempts IS 'Кількість невдалих спроб входу поспіль';
COMMENT ON COLUMN USERS.lock_until IS 'Час завершення блокування через brute-force';


-- 5. ЖУРНАЛ АУДИТУ (Логування подій)
CREATE TABLE AUTH_AUDIT_LOG (
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY,
    event_type  VARCHAR2(50) NOT NULL, -- LOGIN, LOGOUT, PERM_CHANGE, FAIL_LOGIN
    user_id     RAW(16),
    ip_address  VARCHAR2(45),
    user_agent  VARCHAR2(500),
    status      VARCHAR2(20), -- SUCCESS / ERROR
    message     VARCHAR2(1000),
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_AUTH_AUDIT PRIMARY KEY (id)
);

COMMENT ON TABLE AUTH_AUDIT_LOG IS 'Журнал усіх дій, пов’язаних з безпекою';
COMMENT ON COLUMN AUTH_AUDIT_LOG.event_type IS 'Тип події (Вхід, Зміна пароля тощо)';
COMMENT ON COLUMN AUTH_AUDIT_LOG.status IS 'Статус операції: успішно чи помилка';


-- 6. АВТОМАТИЗАЦІЯ (Тригер на оновлення часу)
CREATE OR REPLACE TRIGGER TRG_USERS_UPD_TIME
BEFORE UPDATE ON USERS FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- 7. ПРЕДСТАВЛЕННЯ (VIEW) ДЛЯ ПЕРЕВІРКИ ДОСТУПУ
-- Дозволяє одним запитом отримати всі права користувача
CREATE OR REPLACE VIEW VW_USER_PERMISSIONS AS
SELECT DISTINCT
    u.id as user_id,
    u.username,
    p.perm_code
FROM USERS u
JOIN USER_ROLES ur ON u.id = ur.user_id
JOIN ROLES r ON ur.role_id = r.id
JOIN ROLE_PERMISSIONS rp ON r.id = rp.role_id
JOIN PERMISSIONS p ON rp.perm_id = p.id
WHERE u.is_active = 1 AND u.deleted_at IS NULL;

COMMENT ON TABLE VW_USER_PERMISSIONS IS 'Зручний View для перевірки наявності права у користувача';
